const RouteName = {
    SPLASH_SCREEN: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGINFIRSTSCREEN:'LoginFirstScreen',
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    TAB_NAVIGATOR: "TabNavigators",
    FORGOT_PASSWORD: 'ForgotPassword',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICTION_SCREEN: 'NotificationScreen',
    EDIT_PROFILE_SCREEN: 'EditProfileScreen',   
    PRIVACY_POLICY_SCREEN:'PrivacyPolicyScreen',
    PROFILE_TAB:'ProfileTab',
    LEADTAB:'LeadTab',
    LANGUAGESCREEN:'LanguageScreen',
    ADDMEETING:'AddMeeting',
    ADDTASK:'AddTask',
    ADDCALL:'AddCall',
    ADDLEADS:'AddLeads',
    DEALSTAB:'DealsTab',
    CONTACTSTAB:'ContactsTab',
    ACCOUNTSSCREEN:'AccountsScreen',
    TASKSSCREEN:'TasksScreen',
    MEEETINGSCREEN:'MeetingScreen',
    LOCATIONSCREEN:'LocationScreen',
    CALL:'Call',
    REGISTRATIONSUCCESSFUL:'RegistrationSuccessful',
    OTPSUCCESSFULL:'OtpSuccessful'
}
export default RouteName;